include: 
osx_image: xcode10.2
language: swift
install:
- sudo gem install xcpretty-travis-formatter
script:
- swift test
notifications:
  email: false
  slack:
    rooms:
      secure: w+QfmOOMI89Y20OqHiQYwd7D3bM7ajvNJ4JS++reshykQVBpwVu4zTBUmNfTjLk5n4CnY22JOG81K4v+20VqDAYw0XraWkeugQnLJEKImiWQc/M02aZ6ffHuo07Pp07lC8DUQVfkWhwKBA+flOl43Zba3ge0ewPaS2YW+HVTWeSwpcHrm6gqRK9OJqeipcmBnJfAaaN5YMnUbUuHkF0soxMLVT4pReXilAA2osrtB0GWXvTjz6n7WYQZbY2GwtI8R6vlqzVPz594HO4QNJdquIA7oSq6IQFUxRcEG82z/DhOuBI0kd+pgDUuZpXMmAU+CRy8gWmlAkk+E5QKE0qg7WU8DVTEB6nJwWGtUdWzK6AbYzYw+i6RRHaSrgg0nEz1syIr2aLGyCqQYUcUEGo5RqhxArtp4eiAMFCJhBQw6p9SkA0iikDxmr3ZdW8v6EYd6Xt3bJ/6m2h6F5cXDvr8cKf2Sm/MB4MqpANesgDdBZi1mvN8n6V5Ypaw9jLd+inJU0DAA9HdErsYUQjI9WDvGtrAY1sixvA3MFTXdnEBKD59TyhhYWr76kYY3XvmhuivfysxFwpTYQjybnHhymF1UQi2YvaGPmf8Fz/ntw7FbhqV+Rhp9TYgcX9J5WDjwwgGtwDfit+Mx59F+xfdr/2lgTJWqc8F/E9vm2hQDSxYB+E=
