include: 
osx_image: xcode10.2
language: swift
install:
- sudo gem install xcpretty-travis-formatter
script:
- swift test
notifications:
  email: false
  slack:
    rooms:
      secure: FDjEqq7hPWJt0XllGu1lbwaTdE881DTb7neHMgprfd1H2/q0mwL7O4brteGAJSNpBsPqlaCx0qqhqGUEf0YEjHq0CjCTQe4phqLowOzXJT+887n3+7zS+eLIG3rmxsUqeBo6YIaRnTffd4HCVGJAJ4dOMEhYcHCUER9Q0L7iClDfR0naQaTw1sxfJnAOi8cFVLv5a/IKQPX0W1qhO8vb/876KVLj/ByPJhpOkCZ0OaaysAnqorq5S442+4SgIhrrMGKWte78bMCFYDtVP35HQ45cfCVHjXxWIiG2/jc7nktSqVNjUY7c/7EwV3QA3bNhw3nzDt4COxBFun3JqKnWLT3TuosfFXQaTqVEFl2X7mzjXiw/8a/YvCdWhimcNHZnuqpeKYQ980gUJxCNtkiUAQCpMdzyEB0eOTu8Wy6XNlz/KHjYv9iHA/mKsHvXhMgOjFW5a+HIzqaa9IWkjMiWy/DuFvkwZ+nG+5ulbpBG13+CSZKzB/G/xOIVtwzWbZn9R4+TOYh9agKFey0vHm39euKtb9U3p0mPGNxFIzRtCEHbAc4l5GNZUpG8LLRBCNYLYw7eNQBMJ3K332NkrQbQtfd4b/jd/yfwT/V2odPuy2tUwJ3RQ2kIEmfPHwfKstfVzm5WeSUb5gYgLzfAgYNJ0RZBcvwnme+jJbtqg5v9mpg=
