#if !canImport(ObjectiveC)
import XCTest

extension ExpressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExpressionTests = [
        ("testNamedCapture", testNamedCapture),
        ("testNamedCapturePassedIn", testNamedCapturePassedIn),
        ("testPassedInResults", testPassedInResults),
        ("testPassedInResultsNoMatch", testPassedInResultsNoMatch),
        ("testReturnedResults", testReturnedResults),
    ]
}

extension SubstitutionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubstitutionTests = [
        ("testMultipleSubstitutionGettingLonger", testMultipleSubstitutionGettingLonger),
        ("testMultipleSubstitutionGettingShorter", testMultipleSubstitutionGettingShorter),
        ("testUsingCaptures", testUsingCaptures),
        ("testUsingMainMatch", testUsingMainMatch),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExpressionTests.__allTests__ExpressionTests),
        testCase(SubstitutionTests.__allTests__SubstitutionTests),
    ]
}
#endif
